development:
  adapter: postgresql
  encoding: unicode
  database: links_dev
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: links_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: links_prod
  pool: 5
  username: 
  password:
